language: node_js
node_js:
  - '8'
  - '10'
  - '11'
  - '12'
cache: npm
install:
  - npm install

jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: npm release
      deploy:
        provider: npm
        email: 'wongyouth@gmail.com'
        api_key: '$NPM_TOKEN'
        on:
          tags: true

branches:
  only:
    - master
    - /^v[0-9]+.*$/