language: node_js
node_js:
  - '12'
  - '10'
  - '8'

cache: npm

script:
  - npm test

jobs:
  include:
    - stage: npm release
      node_js: '10'
      deploy:
        provider: npm
        email: 'wongyouth@gmail.com'
        api_key: '$NPM_TOKEN'
        on:
          tags: true

branches:
  only:
    - master
    - /^v[0-9]+.*$/